// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit by hand.

#![allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    unused_parens,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals
)]

use midnight_compact_runtime::*;
use std::marker::PhantomData;

midnight_compact_runtime::check_runtime_version!("0.16.100");

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct Box {
    pub f: Fr,
}
impl Aligned for Box {
    fn alignment() -> Alignment {
        Alignment::concat([&<Fr as Aligned>::alignment()])
    }
}
impl FieldRepr for Box {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.f.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.f.field_size()
    }
}
impl FromFieldRepr for Box {
    const FIELD_SIZE: usize = <Fr as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let f = <Fr as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(Box { f })
    }
}
impl From<Box> for midnight_compact_runtime::Value {
    fn from(s: Box) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.f));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for Box {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.f.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.f.binary_len()
    }
}

pub trait Witnesses<PS> {}
impl<PS> Witnesses<PS> for NoWitnesses {}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    PS: Clone,
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self {
            witnesses,
            _ps: PhantomData,
        }
    }
    pub fn initial_state(
        &self,
        ctx: ConstructorContext<PS>,
    ) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![
            new_cell(Fr::default()),
            new_cell(0u64),
            new_cell_array([Fr::default(); 2]),
            new_cell([0u8; 32]),
            new_cell(midnight_compact_runtime::JubjubPoint::default()),
        ]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, midnight_compact_runtime::ContractAddress::default());
        let tmp = Fr::from(0u64);
        let tmp_0 = 0u64;
        let tmp_1 = [Fr::from(0u64), Fr::from(0u64)];
        let tmp_2 = midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
            midnight_compact_runtime::AlignedValue::from(Fr::from(0u64)),
            midnight_compact_runtime::AlignedValue::from(Fr::from(0u64)),
        ]);
        let tmp_3 = midnight_compact_runtime::hash_to_curve(Fr::from(0u64));
        let ops = OpProgramVerify::<DefaultDB>::new()
            .push(false, new_cell(0u8))
            .push(true, new_cell(tmp.clone()))
            .ins(false, 1)
            .push(false, new_cell(1u8))
            .push(true, new_cell(tmp_0.clone()))
            .ins(false, 1)
            .push(false, new_cell(2u8))
            .push(true, new_cell_array(tmp_1.clone()))
            .ins(false, 1)
            .push(false, new_cell(3u8))
            .push(true, new_cell(tmp_2.clone()))
            .ins(false, 1)
            .push(false, new_cell(4u8))
            .push(true, new_cell(tmp_3.clone()))
            .ins(false, 1)
            .build();

        let results = query_for_verify(&qctx, &ops, ctx.gas_limit.clone(), &ctx.cost_model)?;

        Ok(ConstructorResult {
            current_contract_state: results.context.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }
}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {
    pub fn field_cell(&self) -> Result<Fr, CompactError> {
        let qctx = QueryContext::new(
            self.state.clone(),
            midnight_compact_runtime::ContractAddress::default(),
        );
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(0u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        midnight_compact_runtime::std_lib::decode_fr(av)
    }
    pub fn uint_cell(&self) -> Result<u64, CompactError> {
        let qctx = QueryContext::new(
            self.state.clone(),
            midnight_compact_runtime::ContractAddress::default(),
        );
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(1u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        midnight_compact_runtime::std_lib::decode_u64(av)
    }
    pub fn field_vec(&self) -> Result<[Fr; 2], CompactError> {
        let qctx = QueryContext::new(
            self.state.clone(),
            midnight_compact_runtime::ContractAddress::default(),
        );
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(2u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        midnight_compact_runtime::std_lib::decode_vector_fr::<2>(av)
    }
    pub fn hash_cell(&self) -> Result<[u8; 32], CompactError> {
        let qctx = QueryContext::new(
            self.state.clone(),
            midnight_compact_runtime::ContractAddress::default(),
        );
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(3u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        midnight_compact_runtime::std_lib::decode_bytes::<32>(av)
    }
    pub fn point_cell(&self) -> Result<JubjubPoint, CompactError> {
        let qctx = QueryContext::new(
            self.state.clone(),
            midnight_compact_runtime::ContractAddress::default(),
        );
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(4u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        midnight_compact_runtime::std_lib::decode_jubjub_point(av)
    }
}

pub mod pure_circuits {
    use super::*;

    pub fn idf(x: Fr) -> Result<Fr, CompactError> {
        Ok(x)
    }

    pub fn ret_field_literal() -> Result<Fr, CompactError> {
        Ok(Fr::from(0u64))
    }

    pub fn const_then_call() -> Result<Fr, CompactError> {
        let x = Fr::from(0u64);
        Ok(pure_circuits::idf(Fr::from(0u64))?)
    }

    pub fn struct_literal() -> Result<Box, CompactError> {
        Ok(Box { f: Fr::from(0u64) })
    }

    pub fn some_field_literal() -> Result<Maybe<Fr>, CompactError> {
        Ok(midnight_compact_runtime::std_lib::some(Fr::from(0u64)))
    }

    pub fn hash_zero_literal() -> Result<[u8; 32], CompactError> {
        Ok(midnight_compact_runtime::std_lib::persistent_hash_aligned(
            &[
                midnight_compact_runtime::AlignedValue::from(Fr::from(0u64)),
                midnight_compact_runtime::AlignedValue::from(Fr::from(0u64)),
            ],
        ))
    }

    pub fn native_arg_literal() -> Result<JubjubPoint, CompactError> {
        Ok(midnight_compact_runtime::hash_to_curve(Fr::from(0u64)))
    }

    pub fn uint_to_field(x: u8) -> Result<Fr, CompactError> {
        Ok(Fr::from((x) as u64))
    }

    pub fn u128_rung(x: u128) -> Result<Fr, CompactError> {
        Ok(Fr::from((x) as u128))
    }

    pub fn vector_elt_wise(x: u32) -> Result<[Fr; 2], CompactError> {
        Ok([Fr::from((x) as u64), Fr::from((x) as u64)])
    }

    pub fn ret_u128_field_literal() -> Result<Fr, CompactError> {
        Ok(Fr::from(340282366920938463463374607431768211455u128))
    }

    pub fn ret_huge_field_literal() -> Result<Fr, CompactError> {
        Ok(Fr::from_le_bytes(&[
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00,
        ])
        .expect("Field literal is canonical"))
    }

    pub fn const_huge_field_literal() -> Result<Fr, CompactError> {
        let x = Fr::from_le_bytes(&[
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00,
        ])
        .expect("Field literal is canonical");
        Ok(x)
    }

    pub fn call_arg_huge_field_literal() -> Result<Fr, CompactError> {
        Ok(pure_circuits::idf(
            Fr::from_le_bytes(&[
                0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00,
                0x00, 0x00, 0x00, 0x00,
            ])
            .expect("Field literal is canonical"),
        )?)
    }

    pub fn struct_member_huge_field_literal() -> Result<Box, CompactError> {
        Ok(Box {
            f: Fr::from_le_bytes(&[
                0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00,
                0x00, 0x00, 0x00, 0x00,
            ])
            .expect("Field literal is canonical"),
        })
    }

    pub fn vector_elt_huge_field_literal() -> Result<[Fr; 1], CompactError> {
        Ok([Fr::from_le_bytes(&[
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00,
        ])
        .expect("Field literal is canonical")])
    }

    pub fn cmp_huge_field_literal(x: Fr) -> Result<bool, CompactError> {
        Ok((x
            == Fr::from_le_bytes(&[
                0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00,
                0x00, 0x00, 0x00, 0x00,
            ])
            .expect("Field literal is canonical")))
    }
}
