// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit by hand.

#![allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    unused_parens,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals
)]

use midnight_compact_runtime::*;
use std::marker::PhantomData;

midnight_compact_runtime::check_runtime_version!("0.16.100");

pub trait Witnesses<PS> {}
impl<PS> Witnesses<PS> for NoWitnesses {}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    PS: Clone,
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self {
            witnesses,
            _ps: PhantomData,
        }
    }
    pub fn initial_state(
        &self,
        ctx: ConstructorContext<PS>,
        base: u32,
        q: u32,
    ) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![new_cell(0u32), new_cell(0u64)]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, midnight_compact_runtime::ContractAddress::default());
        let diff = {
            let t = ((q) as u64).wrapping_mul((4) as u64);
            {
                compact_assert!(
                    (((base) as u64) >= t),
                    "result of subtraction would be negative"
                );
                ((base) as u32).wrapping_sub((t) as u32)
            }
        };
        let ops = OpProgramVerify::<DefaultDB>::new()
            .push(false, new_cell(0u8))
            .push(true, new_cell(diff.clone()))
            .ins(false, 1)
            .build();

        let results = query_for_verify(&qctx, &ops, ctx.gas_limit.clone(), &ctx.cost_model)?;

        Ok(ConstructorResult {
            current_contract_state: results.context.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }

    pub fn record_pinned(
        &self,
        ctx: CircuitContext<PS>,
        q: u32,
        y: u32,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let _ = pure_circuits::assert_product_l_e(q, y)?;
        let tmp = 1u16;
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(1u8, true)
            .addi(tmp.clone() as u32)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn record_matching(
        &self,
        ctx: CircuitContext<PS>,
        small: u8,
        big: u32,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        compact_assert!((((small) as u32) == big), "values must match across widths");
        let tmp = 1u16;
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(1u8, true)
            .addi(tmp.clone() as u32)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }
}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {
    pub fn last_diff(&self) -> Result<u32, CompactError> {
        let qctx = QueryContext::new(
            self.state.clone(),
            midnight_compact_runtime::ContractAddress::default(),
        );
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(0u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        midnight_compact_runtime::std_lib::decode_u32(av)
    }
    pub fn mixed_ops(&self) -> Result<u64, CompactError> {
        let qctx = QueryContext::new(
            self.state.clone(),
            midnight_compact_runtime::ContractAddress::default(),
        );
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(1u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        midnight_compact_runtime::std_lib::decode_u64(av)
    }
}

pub mod pure_circuits {
    use super::*;

    pub fn assert_product_l_e(q: u32, y: u32) -> Result<(), CompactError> {
        let t = ((q) as u64).wrapping_mul((4) as u64);
        compact_assert!((t <= ((y) as u64)), "product must not exceed the bound");
        Ok(())
    }

    pub fn assert_product_l_t(q: u32, y: u32) -> Result<(), CompactError> {
        let t = ((q) as u64).wrapping_mul((4) as u64);
        compact_assert!((t < ((y) as u64)), "product must stay below the bound");
        Ok(())
    }

    pub fn assert_product_g_t(q: u32, y: u32) -> Result<(), CompactError> {
        let t = ((q) as u64).wrapping_mul((4) as u64);
        compact_assert!((t > ((y) as u64)), "product must exceed the bound");
        Ok(())
    }

    pub fn assert_product_g_e(q: u32, y: u32) -> Result<(), CompactError> {
        let t = ((q) as u64).wrapping_mul((4) as u64);
        compact_assert!((t >= ((y) as u64)), "product must reach the bound");
        Ok(())
    }

    pub fn assert_product_e_q(q: u32, y: u32) -> Result<(), CompactError> {
        compact_assert!(
            (((q) as u64).wrapping_mul((4) as u64) == ((y) as u64)),
            "product must equal the bound"
        );
        Ok(())
    }

    pub fn assert_product_n_e(q: u32, y: u32) -> Result<(), CompactError> {
        compact_assert!(
            (((q) as u64).wrapping_mul((4) as u64) != ((y) as u64)),
            "product must differ from the bound"
        );
        Ok(())
    }

    pub fn sum_mixed(q: u32, n: u8) -> Result<u64, CompactError> {
        Ok(((q) as u64).wrapping_add((n) as u64))
    }

    pub fn product_mixed(q: u32, m: u8) -> Result<u64, CompactError> {
        Ok(((q) as u64).wrapping_mul((m) as u64))
    }

    pub fn guarded_diff(y: u32, q: u32) -> Result<u32, CompactError> {
        let t = ((q) as u64).wrapping_mul((4) as u64);
        compact_assert!(
            (((y) as u64) >= t),
            "result of subtraction would be negative"
        );
        Ok(((y) as u32).wrapping_sub((t) as u32))
    }
}
